version: '3'

services:
    liquidd:
        build:
            context: .
            dockerfile: Dockerfile.liquid
    loyalty:
        build:
            context: .
        volumes:
            - '.:/loyaltytoken'
    nginx:
        build:
            context: ./nginx
        ports:
            - '8888:8888'
        depends_on:
            - 'loyalty'
