FROM ubuntu:18.04

RUN apt-get update -q && \
    apt-get install -qy  git make g++ autoconf libtool pkg-config bsdmainutils libboost-all-dev libssl-dev libevent-dev libdb++-dev net-tools lsof && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get autoremove -y && \
    apt-get clean
WORKDIR /liquid
ADD ./liquid /liquid
RUN ./autogen.sh && ./configure --enable-static --disable-shared --disable-tests --with-incompatible-bdb
RUN make -j4
VOLUME /root
COPY liquid.conf /liquid/src
CMD /liquid/src/liquidd -conf=/liquid/src/liquid.conf
